/**
 * Building the SDK.
 *
 * Two outputs and a declaration file: CommonJS for `require`, ESM for `import`,
 * and types generated by tsc from src/types.ts, so the published declarations
 * are always the source they were built from.
 */
import { build } from "esbuild"
import { execFileSync } from "node:child_process"
import { rmSync } from "node:fs"
import { createRequire } from "node:module"

rmSync("dist", { recursive: true, force: true })

const shared = {
    entryPoints: ["src/index.ts"],
    bundle: true,
    platform: "neutral",
    target: "es2022",
    sourcemap: true,
}

// .cjs, not .js: the package is "type": "module", so Node would read a .js file
// as an ES module and `require` of it would fail on `module.exports`.
await build({ ...shared, format: "cjs", outfile: "dist/index.cjs" })
await build({ ...shared, format: "esm", outfile: "dist/index.mjs" })

// Declarations from the source. `--emitDeclarationOnly` so tsc does not race
// esbuild for the JavaScript.
//
// tsc is invoked through node with its own entry point rather than through npx.
// npx is a .cmd on Windows and execFileSync will not spawn one, which fails
// with EINVAL and a stack that says nothing about the cause.
execFileSync(
    process.execPath,
    [createRequire(import.meta.url).resolve("typescript/bin/tsc"), "--project", "tsconfig.build.json"],
    { stdio: "inherit" },
)

console.log("@visualautomate/plugin-sdk → dist/")
