/**
 * Building the CLI.
 *
 * One bundled file with the SDK inside it, so `npm i -g @visualautomate/cli` is
 * the only install anybody does. esbuild is a real dependency rather than a dev
 * one: `visualautomate test` and `push` compile the author's TypeScript, so the
 * bundler ships with the tool.
 *
 * The type declarations a scaffolded plugin gets are generated from the SDK's
 * own source here, at build time. That is the whole reason a plugin directory
 * needs no node_modules: the types are written into it, and they cannot drift
 * from the SDK because they are copied out of it every time this runs.
 */
import { build } from "esbuild"
import { readFile, writeFile, rm } from "node:fs/promises"

const { version } = JSON.parse(await readFile("package.json", "utf8"))

const types = await readFile("../plugin-sdk/src/types.ts", "utf8")

await writeFile(
    "src/declarations.ts",
    "// GENERATED by build.mjs from ../plugin-sdk/src/types.ts — do not edit.\n" +
        "// A scaffolded plugin imports these from ./visualautomate, which is this\n" +
        "// file's contents written into the project by `visualautomate init`.\n" +
        "export const TYPE_DECLARATIONS = " +
        JSON.stringify(types) +
        "\n",
)

await rm("dist", { recursive: true, force: true })

await build({
    entryPoints: ["src/index.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    outfile: "dist/index.js",
    banner: { js: "#!/usr/bin/env node" },
    // esbuild loads its own binary at run time and cannot be bundled into one
    // file; it stays a dependency and is resolved normally.
    external: ["esbuild"],
    // The SDK comes in from source rather than from node_modules, so the
    // published CLI carries exactly the SDK in this repository at the same
    // version, rather than whatever version happened to resolve.
    alias: { "@visualautomate/plugin-sdk": "../plugin-sdk/src/index.ts" },
    // `va --version`, and the sandbox image tag `--docker` asks for.
    define: { __CLI_VERSION__: JSON.stringify(version) },
})

console.log("@visualautomate/cli → dist/index.js")
